#!/usr/bin/env python3
"""Generate derived config files from config/config.yaml + config/.env.secrets.

Outputs:
  .env                                          Docker Compose environment variables
  xr_runtime/streaming/mediamtx.yml             MediaMTX config
  xr_runtime/speech/tts_pusher/tts_models.yaml  TTS model definitions
"""

import os
import sys
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parent.parent
CONFIG_FILE = ROOT / "config" / "config.yaml"


# ---------------------------------------------------------------------------
# Secrets loader
# ---------------------------------------------------------------------------

def load_secrets(secrets_path: Path) -> dict:
    secrets = {}
    if not secrets_path.exists():
        return secrets
    with open(secrets_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                secrets[key.strip()] = value.strip()
    return secrets


def load_config() -> dict:
    with open(CONFIG_FILE) as f:
        return yaml.safe_load(f)


# ---------------------------------------------------------------------------
# .env (Docker Compose runtime)
# ---------------------------------------------------------------------------

def generate_env(cfg: dict, secrets: dict) -> str:
    rt = cfg.get("runtime", {})
    sp = cfg.get("speech", {})
    dash = cfg.get("dashboard", {})
    nvr = cfg.get("nvr", {})
    nat = cfg.get("nat_server", {})

    streaming = rt.get("streaming", {})
    stt = sp.get("stt", {})
    tts = sp.get("tts", {})
    nvr_creds = nvr.get("credentials", {})
    shinobi = nvr.get("shinobi", {})

    nat_url = nat.get("url", "ws://localhost:8002/ws")

    lines = [
        "# Auto-generated by scripts/configure.py -- do not edit manually.",
        "",
        "# Secrets",
        f"NGC_API_KEY={secrets.get('NGC_API_KEY', '')}",
        f"DASHSCOPE_API_KEY={secrets.get('DASHSCOPE_API_KEY', '')}",
        "",
        "# Runtime",
        f"NUM_CAMERAS={rt.get('num_cameras', 1)}",
        f"STREAMING_METHOD={streaming.get('method', 'mediamtx')}",
        f"DEFAULT_FRAMERATE={streaming.get('framerate', 30)}",
        f"MEDIAMTX_SERVICE_NAME={streaming.get('mediamtx_service_name', 'mediamtx')}",
        "",
        "# Ports",
        f"GRPC_PORT=5050",
        f"WEB_PORT={dash.get('port', 5001)}",
        f"TTS_PUSHER_PORT=5100",
        f"TTS_MIXER_PORT=5004",
        f"NVR_PORT={nvr.get('port', 8088)}",
        "",
        "# NAT Server (external)",
        f"NAT_SERVER_URL={nat_url}",
        "",
        "# Speech",
        f"STT_HOST={stt.get('host', 'localhost')}",
        f"STT_PORT={stt.get('port', 50051)}",
        f"STT_PROTOCOL={stt.get('protocol', 'grpc')}",
        f"ENABLE_TTS={'true' if tts.get('enabled', True) else 'false'}",
        f"TTS_PROVIDER={tts.get('provider', 'vibevoice')}",
        "",
        "# TTS Providers",
        f"RIVA_HOST={tts.get('riva', {}).get('host', 'riva-server')}",
        f"RIVA_PORT={tts.get('riva', {}).get('port', 50051)}",
        f"ENABLE_RIVA_TTS={'true' if tts.get('provider') == 'riva' else 'false'}",
        f"ENABLE_DASHSCOPE_TTS={'true' if tts.get('provider') == 'qwen' else 'false'}",
        "",
        "# NVR",
        f"ENABLE_NVR={'true' if nvr.get('enabled', False) else 'false'}",
        f"MAIL={nvr_creds.get('email', 'viture@test.com')}",
        f"PASSWORD={nvr_creds.get('password', 'test1234')}",
        f"GROUP_KEY={shinobi.get('group_key', '')}",
        f"UNIQUE_ID={shinobi.get('unique_id', '')}",
        f"API_KEY={shinobi.get('api_key', '')}",
        f"STORAGE_SIZE={shinobi.get('storage_size', 300000)}",
        "",
        "# Docker Images",
        f"RTSP_IMAGE=labos_streaming:latest",
        "",
        "# Audio Forwarding",
        f"FORWARD_AUDIO=false",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# MediaMTX config (XR-side)
# ---------------------------------------------------------------------------

def generate_mediamtx_config() -> str:
    lines = [
        "# Auto-generated by scripts/configure.py",
        "",
        "api: yes",
        "apiAddress: 0.0.0.0:9997",
        "",
        "rtsp: yes",
        "rtspAddress: :8554",
        "",
        "hls: yes",
        "hlsAddress: :8888",
        "",
        "webrtc: yes",
        "webrtcAddress: :8889",
        "",
        "paths:",
        "  all:",
        "    source: publisher",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# TTS models config
# ---------------------------------------------------------------------------

def generate_tts_models(cfg: dict) -> dict:
    tts = cfg.get("speech", {}).get("tts", {})
    riva_cfg = tts.get("riva", {})
    qwen_cfg = tts.get("qwen", {})
    vibe_cfg = tts.get("vibevoice", {})

    return {
        "models": {
            "riva": {
                "name": "Riva TTS",
                "provider": "riva",
                "description": "NVIDIA Riva gRPC TTS",
                "type": "grpc",
                "enabled": tts.get("provider") == "riva",
                "host": riva_cfg.get("host", "riva-server"),
                "port": riva_cfg.get("port", 50051),
                "default_voice": "English-US.Female-1",
                "sample_rate": 48000,
                "channels": 1,
                "voices": [{"name": "English-US.Female-1", "language": "en", "sample_rate": 48000}],
            },
            "qwen-tts": {
                "name": "Qwen TTS",
                "provider": "qwen",
                "description": "Alibaba DashScope Qwen TTS",
                "type": "http",
                "enabled": tts.get("provider") == "qwen",
                "base_url": qwen_cfg.get("base_url", "https://dashscope.aliyuncs.com/api/v1"),
                "api_key_env": "DASHSCOPE_API_KEY",
                "default_voice": "loongstella-v1",
                "sample_rate": 24000,
                "channels": 1,
                "voices": [{"name": "loongstella-v1", "language": "zh", "sample_rate": 24000}],
            },
            "vibevoice": {
                "name": "VibeVoice TTS",
                "provider": "vibevoice",
                "description": "VibeVoice HTTP TTS server",
                "type": "http",
                "enabled": tts.get("provider") == "vibevoice",
                "host": vibe_cfg.get("host", "tts"),
                "port": vibe_cfg.get("port", 8050),
                "default_voice": "en-Emma_woman",
                "sample_rate": 44100,
                "channels": 1,
                "voices": [{"name": "en-Emma_woman", "language": "en", "sample_rate": 44100}],
            },
        }
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if not CONFIG_FILE.exists():
        print(f"Error: {CONFIG_FILE} not found", file=sys.stderr)
        print("  Run install.sh/install.bat first, or copy config.yaml.example to config.yaml")
        sys.exit(1)

    print("Loading config/config.yaml ...")
    cfg = load_config()

    secrets_file = cfg.get("global", {}).get("secrets_file", "config/.env.secrets")
    secrets_path = ROOT / secrets_file
    secrets = load_secrets(secrets_path)

    # .env
    env_content = generate_env(cfg, secrets)
    env_path = ROOT / ".env"
    env_path.write_text(env_content)
    print(f"  Generated {env_path}")

    # mediamtx.yml
    mtx_content = generate_mediamtx_config()
    mtx_path = ROOT / "xr_runtime" / "streaming" / "mediamtx.yml"
    mtx_path.write_text(mtx_content)
    print(f"  Generated {mtx_path}")

    # tts_models.yaml
    tts_models = generate_tts_models(cfg)
    tts_path = ROOT / "xr_runtime" / "speech" / "tts_pusher" / "tts_models.yaml"
    tts_path.parent.mkdir(parents=True, exist_ok=True)
    with open(tts_path, "w") as f:
        yaml.dump(tts_models, f, default_flow_style=False, sort_keys=False)
    print(f"  Generated {tts_path}")

    print("Done.")


if __name__ == "__main__":
    main()
